### ISSUE TITLE
Review: JS Advanced

### ISSUE THREAD

**Issue by AlekseiIvshin** [kmisha/epam_labs#1]
Task1 = 2 asyncCompare - внутри не взаимоисключающие вызовы setTimeout, то есть при ошибке 2-ой setTimeout запустить таймер, результат которого не будет использован

Task2 = 2

Task3 = 2

Task4 = 2

Task5 - Все ок, но не надо стопать интервал через Х время другим интервалом или таймаутом. Нет гарантии что он отработает именно нужное количество раз. Лучше использовать счетчик вызовов внутри. Например https://jsbin.com/tiyomiquzu/edit?js,console 

**Итоговая оценка 2**

**Comment by kmisha** [comment]
Task 1. Исправил.
Добавил ветку условного ветвления else.
else {
setTimeout(() => resolve(compare(val1, val2)), 1000);
}

**Comment by kmisha** [comment]
Оценка устраивает. Тикет закрываю.
