### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [kmisha/epam_labs#2]
Task1 - 1
Task2 - 0 - Проблема в переопределении метода openDoor и closeDoor для MonsterTruck: он не использует родительский метод
Task3 - 0
- См. Task2
- Наследование предполагает, что проверка instanceof со всеми родительскими классами будет возвращать true. Например, `new MonsterTruck() instanceof Vehical -> true`

Task4 - 2 - `r instanceof Animal` - должно возвращать true

**Итоговая оценка 0**

**Comment by kmisha** [comment]
Task4 Исправил. Добавил:
Rabbit.prototype = Object.create(Animal.prototype);
Rabbit.prototype.constructor = Rabbit;
console.log(r instanceof Animal);

**Comment by kmisha** [comment]
Task 2. Исправил. Добавил вызов родительского метода.
setTimeout(Car.prototype.openDoor.bind(this), 1000); в openDoor
setTimeout(Car.prototype.closeDoor.bind(this), 1000); в closeDoor

**Comment by kmisha** [comment]
Task 3. Исправил. Добавил наследование через свойство prototype:
MonsterTruck.prototype = Object.create(Car.prototype);
MonsterTruck.prototype.constructor = MonsterTruck;
и аналогично
Car.prototype = Object.create(Vehical.prototype);
Car.prototype.constructor = Car;

Bike.prototype = Object.create(Vehical.prototype);
Bike.prototype.constructor = Bike;

Исправил перезагрузку методов openDoor и closeDoor:
        // save Car.openDoor
	var parentopenDoor = this.openDoor;
	this.openDoor = function() {
		setTimeout(parentopenDoor.bind(this), 1000);
	};
	// save Car.closeDoor
	var parentCloseDoor = this.closeDoor;
	this.closeDoor = function() {
		setTimeout(parentCloseDoor.bind(this), 1000);
	};

**Comment by kmisha** [comment]
А почему за Task1 - 1?

**Comment by AlekseiIvshin** [comment]
Отлично! Прекрасный подход к работе с git!

Task1 - 1
Task2 - 1
Task3 - 1
Task4 - 2

**Итоговая оценка 2**

**Comment by kmisha** [comment]
Задание сдано. Тикет закрываю.
