### ISSUE TITLE
Review: JS Design patterns

### ISSUE THREAD

**Issue by nikromiks** [kmisha/epam_labs#3]
- Разбить классы в задании по отдельным файлам, сделать отдельный файл раннер, где будут вызываться все классы из задания.
- таск 2:
1)
`//setTimeout(this.eventFromWallet.bind(this.nextWallet,minus), Math.random() * 500);
      setTimeout(() => {this.nextWallet.eventFromWallet(minus);} , Math.random() * 500);`
Как можно избавится от стрелочной функции и чтобы все работало как прежде? 
Переделай пожалуйста

2)
`
Wallet.prototype.eventFromWallet = function(plus) {
  this.amount = this.amount + plus;
  console.log('Wallet is: ' + this.name + ' account: ' + this.amount);
  this.send();   
}
`
<= договаривались же вызывать метод `send()` снаружи, как он тут очутился?

**Comment by kmisha** [comment]
Task 2. [Убрал стрелочную функцию](https://github.com/kmisha/epam_labs/commit/21e4e40054155f6c64a95018ff5eab1426c3c747)
Можно ещё написать вот так:
`this.eventFromWallet.bind(this.nextWallet,minus)`

**Comment by kmisha** [comment]
Оценка устраивает. Тикет закрываю.
