### ISSUE TITLE
super(...)

### ISSUE THREAD

**Issue by aleksandr-konovalov** [kmisha/epam_labs#4]
Необходимо исправить использование super. Если в конструктор передаётся некоторое кол-во аргументов, то можно взять их spread оператором и вызвать с super так же.
constructor(...args) {
  super(...args);
}
Так не надо будет запариваться об изменении кол-ва аргументов у родителя, если они изменятся.

**Comment by kmisha** [comment]
Привет! [Исправил.](https://github.com/kmisha/epam_labs/commit/2a3a1fe11951fc316ca65c7164500b3c01a63bdb)
